### ISSUE TITLE
During wrap step, generate peercoin URI

### ISSUE THREAD

**Issue by peerchemist** [peercoin/wrapmeister-ui#10]
Example of an URI:

> peercoin:mjmgQXtg9ACBUq2YKL8tdmpJF6S1cWZ5Nr

**Comment by jointhepartypooper** [comment]
Please explain like i am 5

what can you do with a string such as: peercoin:mjmgQXtg9ACBUq2YKL8tdmpJF6S1cWZ5Nr

**Comment by peerchemist** [comment]
If you have properly installed peercoin-qt on your system, with mime info set all that jazz you can click on URI and it will automatically bring up the peercoin-qt/send_tab with address and amount already inputed.

**Comment by peerchemist** [comment]
Full URI example:

> peercoin:muuaf6eHen5dP2HMjttW7KNFJYjGzWaZYA?amount=10.000000&message=wrapmeister_aug_20_20%3A44

**Comment by peerchemist** [comment]
Google hit on something which looks like it does it: https://github.com/coins/bitcoin-uri-js

**Comment by jointhepartypooper** [comment]
so when wrap responses with a peercoinaddress, encode it with somethin like https://github.com/bitcoinjs/bip21/blob/master/index.js and put that in the QR-code ?

**Comment by peerchemist** [comment]
Qr code and/or uri, like a click able link.

**Comment by jointhepartypooper** [comment]
see commit 614edd8b70b3d6f2acaf43ce62ff3a0989e7c242

**Comment by peerchemist** [comment]
Awesome.
