### ISSUE TITLE
Frontend seems to think that segwit address is invalid

### ISSUE THREAD

**Issue by peerchemist** [peercoin/wrapmeister-ui#15]
It seems it can't parse peercoin testnet segwit address.

**Comment by jointhepartypooper** [comment]
please provide an example. I dont know what a segwit address is. Any npm library that supports it?

**Comment by peerchemist** [comment]
> tpc1qrq9n4dahfk620l8ue8xhkru0hqfhsmpzgyj5u6

That's a segwit address.

This library seems to support it, but it will take some patching: https://github.com/ognus/wallet-address-validator

Like this: https://github.com/ognus/wallet-address-validator/pull/74

Peercoin segwit prefixes are `pc` and `ptc`.

**Comment by jointhepartypooper** [comment]
I copied the entire function to a folder: crypto
please confirm the prefix is tpc and not ptc: tpc1qrq9n4dahfk620l8ue8xhkru0hqfhsmpzgyj5u6.

**Comment by jointhepartypooper** [comment]
a9d62f9a9f0331336ec0df49e9e7d86315b492ff

**Comment by peerchemist** [comment]
Left you a comment on latest commit.
